/** Monthly scheme-bonus commission (₹) — replace with API. Keys: Electronics | EV */
export const SCHEME_EARNINGS_MONTHLY_RUPEES = {
  Electronics: { my: 2400, store: 8200 },
  EV: { my: 1950, store: 6100 },
};

/** Demo scheme catalogue — replace with API response mapping in schemeService. */
export const SCHEME_MOCK_DATA = [
  {
    id: "sch-xiaomi-march-sprint",
    name: "Xiaomi March Sprint",
    brand: "Xiaomi",
    validityStart: "2026-03-01",
    validityEnd: "2026-03-31",
    targetMetric: "policy_count",
    targetValue: 50,
    payoutStructure: "tiered",
    flatPayoutAmount: null,
    tiers: [
      { threshold: 10, payout: 500, achieved: true },
      { threshold: 25, payout: 1500, achieved: true },
      { threshold: 50, payout: 5000, achieved: false },
    ],
    eligibilityProducts: ["2Y Total Protection", "1Y ALD + EW", "2Y Money Back"],
    eligibilitySellerLevels: ["Promoter", "Dealer", "Distributor"],
    progress: { mySales: 18, storeTotal: 42, targetValue: 50 },
    status: "active",
    domain: "Electronics",
    productCategory: "Electronics",
    staffBreakdown: [
      { staffName: "Arjun K.", sales: 12 },
      { staffName: "Priya N.", sales: 9 },
      { staffName: "Rahul M.", sales: 8 },
      { staffName: "Others", sales: 13 },
    ],
  },
  {
    id: "sch-oppo-attach-q1",
    name: "Oppo Attach Accelerator",
    brand: "Oppo",
    validityStart: "2026-01-15",
    validityEnd: "2026-03-28",
    targetMetric: "attach_rate",
    targetValue: 72,
    payoutStructure: "flat",
    flatPayoutAmount: 3500,
    tiers: null,
    eligibilityProducts: ["ALD + EW", "Total Protection"],
    eligibilitySellerLevels: ["Promoter", "Dealer"],
    progress: { mySales: 68, storeTotal: 64, targetValue: 72 },
    status: "expiring_soon",
    domain: "Electronics",
    productCategory: "Electronics",
    staffBreakdown: [
      { staffName: "Arjun K.", sales: 71 },
      { staffName: "Priya N.", sales: 65 },
      { staffName: "Rahul M.", sales: 58 },
    ],
  },
  {
    id: "sch-plan-mix-apr",
    name: "Premium Plan Mix — April",
    brand: "GT",
    validityStart: "2026-04-01",
    validityEnd: "2026-04-30",
    targetMetric: "plan_type_mix",
    targetValue: 40,
    payoutStructure: "tiered",
    flatPayoutAmount: null,
    tiers: [
      { threshold: 15, payout: 800, achieved: false },
      { threshold: 40, payout: 3200, achieved: false },
    ],
    eligibilityProducts: ["2Y Total Protection", "Money Back"],
    eligibilitySellerLevels: ["Promoter", "Dealer", "Distributor"],
    progress: { mySales: 6, storeTotal: 14, targetValue: 40 },
    status: "upcoming",
    domain: "Electronics",
    productCategory: "Electronics",
    staffBreakdown: [
      { staffName: "Arjun K.", sales: 5 },
      { staffName: "Priya N.", sales: 4 },
      { staffName: "Rahul M.", sales: 5 },
    ],
  },
  {
    id: "sch-hero-vida-ecw",
    name: "Hero Vida ECW Booster",
    brand: "Hero Vida",
    validityStart: "2026-02-01",
    validityEnd: "2026-02-28",
    targetMetric: "policy_count",
    targetValue: 30,
    payoutStructure: "tiered",
    flatPayoutAmount: null,
    tiers: [
      { threshold: 10, payout: 2000, achieved: true },
      { threshold: 20, payout: 4500, achieved: true },
      { threshold: 30, payout: 9000, achieved: true },
    ],
    eligibilityProducts: ["ECW", "EBW"],
    eligibilitySellerLevels: ["EV Dealer", "Distributor", "Brand Admin"],
    progress: { mySales: 14, storeTotal: 28, targetValue: 30 },
    status: "expired",
    domain: "EV",
    productCategory: "EV",
    staffBreakdown: [
      { staffName: "Arjun K.", sales: 10 },
      { staffName: "Suresh P.", sales: 8 },
      { staffName: "Kavya R.", sales: 10 },
    ],
  },
];
